module.exports = [
    {
        name: "Blue Dream",
        strain: "Hybrid",
        description: "Crossing a Blueberry indica with the sativa Haze, Blue Dream balances full-body relaxation with gentle cerebral invigoration. Novice and veteran consumers alike enjoy the level effects of Blue Dream, which ease you gently into a calm euphoria.",
        strength: 20.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/661836/b/blue-dream__primary_d12b.jpg",
        rating: 4,
    },
    {
        name: "Sour Diesel",
        strain: "Sativa",
        description: "Stress, pain, and depression fade away in long-lasting relief that makes Sour Diesel a top choice among medical patients.",
        strength: 22.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1002134/b/sour-diesel__primary_958a.jpg",
        rating: 4,
    },
    {
        name: "Girl Scout Cookies",
        strain: "Hybrid",
        description: "GSC launches you to euphoria’s top floor where full-body relaxation meets a time-bending cerebral space.",
        strength: 20.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1002672/b/girl-scout-cookies__primary_80db.jpg",
        rating: 4,
    },
    {
        name: "Green Crack",
        strain: "Sativa",
        description: "Few strains compare to Green Crack’s sharp energy and focus as it induces an invigorating mental buzz that keeps you going throughout the day.",
        strength: 16,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/679949/b/green-crack__primary_d4a7.jpg",
        rating: 4,
    },
    {
        name: "OG Kush",
        strain: "Hybrid",
        description: "OG Kush is cherished for its ability to crush stress under the weight of its heavy euphoria.",
        strength: 22.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/651405/b/og-kush__primary_a6a5.jpg",
        rating: 4,
    },
    {
        name: "GrandDaddy Purple",
        strain: "Indica",
        description: "Its potent effects are clearly detectable in both mind and body, delivering a fusion of cerebral euphoria and physical relaxation.",
        strength: 23,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1000259/b/granddaddy-purple__primary_8644.jpg",
        rating: 4,
    },
    {
        name: "Maui Waui",
        strain: "Sativa",
        description: "It provides a light and pleasant body numbing sensation as well as a strong case of the stereotypical 'munchies",
        strength: 19,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/510634/b/maui-waui__primary_c4fa.jpg",
        rating: 4,
    },
    {
        name: "Jack Herer",
        strain: "Sativa",
        description: "Jack Herer captures both the cerebral elevation associated with sativas and the heavy resin production of indicas",
        strength: 20,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1002513/b/jack-herer__primary_5624.jpg",
        rating: 4,
    },
    {
        name: "White Widow",
        strain: "Hybrid",
        description: "A powerful burst of euphoria and energy breaks through immediately, stimulating both conversation and creativity",
        strength: 21.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1002390/b/white-widow__primary_488b.jpg",
        rating: 4,
    },
    {
        name: "Gorilla Glue #4",
        strain: "Hybrid",
        description: "a potent hybrid strain that delivers heavy-handed euphoria and relaxation, leaving you feeling “glued” to the couch.",
        strength: 23,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/1003601/b/gorilla-glue--4__primary_a05e.jpg",
        rating: 5,
    },
    {
        name: "Bubba Kush",
        strain: "Indica",
        description: "Sweet hashish flavors with subtle notes of chocolate and coffee come through on the exhale, delighting the palate as powerful relaxation takes over.",
        strength: 21.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/670668/b/bubba-kush__primary_8368.jpg",
        rating: 4,
    },
    {
        name: "Northern Lights",
        strain: "Indica",
        description: "Pungently sweet, spicy aromas radiate from the crystal-coated buds, which sometimes reveal themselves in hues of purple.",
        strength: 26,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/675787/b/northern-lights__primary_d3f6.jpg",
        rating: 4,
    },
    {
        name: "Blue Cheese",
        strain: "Indica",
        description: "The sweet and savory smells of berry and blue cheese combine to create a creamy, unique flavor reminiscent of the original Cheese.",
        strength: 17.5,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/669514/b/blue-cheese__primary_7907.jpg",
        rating: 4,
    },
    {
        name: "Durban Poison",
        strain: "Sativa",
        description: "Durban Poison is the perfect strain to help you stay productive through a busy day, when exploring the outdoors, or to lend a spark of creativity.",
        strength: 20,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/544060/b/durban-poison__primary_5a5d.jpg",
        rating: 5,
    },
    {
        name: "Pineapple Express",
        strain: "Hybrid",
        description: "This hard-hitting sativa-dominant hybrid provides a long-lasting energetic buzz perfect for productive afternoons and creative escapes.",
        strength: 20,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/645009/b/pineapple-express__primary_6318.jpg",
        rating: 4,
    },
    {
        name: "Purple Kush",
        strain: "Indica",
        description: "Blissful, long-lasting euphoria blankets the mind while physical relaxation rids the body of pain, sleeplessness, and stress.",
        strength: 21,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/641933/b/purple-kush__primary_ca8a.jpg",
        rating: 4,
    },
    {
        name: "Strawberry Cough",
        strain: "Sativa",
        description: "The skunky, berry flavors will capture your senses while the cerebral, uplifting effects provide an aura of euphoria that is sure to leave a smile on your face.",
        strength: 22,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/572587/b/strawberry-cough__primary_120d.jpg",
        rating: 4,
    },
    {
        name: "Cherry Pie",
        strain: "Hybrid",
        description: "With buds that are dense and full of orange hairs and a touch of purple, this strain smells of sweet and sour cherry pie.",
        strength: 20,
        imgUrl: "https://d3ix816x6wuc0d.cloudfront.net/cdn/strain-photo/679530/b/cherry-pie__primary_d915.jpg",
        rating: 4,
    }
]